AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recording API demo for Amazon Connect

Mappings: 
  FunctionMap:
      Configuration:
          S3Bucket: "amazon-connect-blogs2"
          S3Key: "2020/contactflows/"
 
Parameters:
  CADS3BucketForWebSite:
    Type: String
    AllowedPattern: '(?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)'
    ConstraintDescription: 'Invalid S3 Bucket name'
    Description: Enter the (globally unique) name you would like to use for the Amazon S3 bucket where we will store the website assets and the sample contact flow. This template will fail to deploy if the bucket name you chose is currently in use.

  backupDDBTable:
    Type: String
    Description: >
        The name of the DynamoDB Table contact flows will be backed up (Ensure you do not have a table with this name already).

  arnMappingDDBTable:
    Type: String
    Description: >
        The name of the DynamoDB Table which maintains ARN mappings to target environment (Ensure you do not have a table with this name already).
            
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Amazon S3 Configuration 
        Parameters:
          - CADS3BucketForWebSite
      - Label:
          default: Amazon DynamoDB Configuration 
        Parameters:
          - backupDDBTable
          - arnMappingDDBTable
          
    ParameterLabels:
      CADS3BucketForWebSite:
        default: Website Bucket Name
      backupDDBTable:
        default: Backup table 
      arnMappingDDBTable:
        default: ARN Mappings

Outputs:
  CloudfrontEndpoint:
      Description: Endpoint for Cloudfront distribution
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt [CADCloudFrontDistribution, DomainName]
          - '/connectflows.html'
      
  DDBForBackup:
      Description: Endpoint for Cloudfront distribution
      Value: !Ref backupDDBTable
      
  DDBForARNMapping:
      Description: Endpoint for Cloudfront distribution
      Value: !Ref arnMappingDDBTable
  
Resources:
    CFABackupDDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:  !Ref backupDDBTable
        AttributeDefinitions:
          -
            AttributeName: "flowId"
            AttributeType: "S"
          -
            AttributeName: "Arn"
            AttributeType: "S"
          
        KeySchema:
          -
            AttributeName: "flowId"
            KeyType: "HASH"
          -
            AttributeName: "Arn"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits:
              1
          WriteCapacityUnits:
              1
        PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: True
        SSESpecification:
            SSEEnabled: True
        LocalSecondaryIndexes: 
        - 
          IndexName: "backupLSI"
          KeySchema: 
            - 
              AttributeName: "flowId"
              KeyType: "HASH"
            - 
              AttributeName: "Arn"
              KeyType: "RANGE"
              
          Projection:
             NonKeyAttributes:
               - "flowId"
               - "Arn"
             ProjectionType: "INCLUDE"

    CFAARNMappingDDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:  !Ref arnMappingDDBTable
        AttributeDefinitions:
          -
            AttributeName: "sourceARN"
            AttributeType: "S"
          -
            AttributeName: "targetARN"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "sourceARN"
            KeyType: "HASH"
          -
            AttributeName: "targetARN"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits:
              1
          WriteCapacityUnits:
              1
        PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: True
        SSESpecification:
            SSEEnabled: True
        LocalSecondaryIndexes: 
        - 
          IndexName: "arnmapLSI"
          KeySchema: 
            - 
              AttributeName: "sourceARN"
              KeyType: "HASH"
            - 
              AttributeName: "targetARN"
              KeyType: "RANGE"
          Projection:
             NonKeyAttributes:
               - "sourceARN"
               - "targetARN"
             ProjectionType: "INCLUDE"
           
    createWebSiteS3Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Ref CADS3BucketForWebSite
            PublicAccessBlockConfiguration:
                BlockPublicAcls: False
                BlockPublicPolicy: False
                IgnorePublicAcls: False
                RestrictPublicBuckets: False
            WebsiteConfiguration:
                IndexDocument: connectflows.html
                ErrorDocument: error.html
 
 
    CADs3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        DependsOn:
            - CADCloudFrontDistributionAccessIdentity
        Properties:
            Bucket: !Ref createWebSiteS3Bucket
            PolicyDocument:
                Statement:
                    -
                        Action:
                            - "s3:GetObject"
                        Effect: "Allow"
                        Principal:
                            CanonicalUser:
                                Fn::GetAtt: [ CADCloudFrontDistributionAccessIdentity , S3CanonicalUserId ]
                        Resource:
                            !Sub ${createWebSiteS3Bucket.Arn}/contactflowsite/*

    CADCloudFrontDistributionAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
          CloudFrontOriginAccessIdentityConfig:
            Comment: 'CloudFront endpoint for contact flows s3'
            
    CADCloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
          DistributionConfig:
            Origins:
            - DomainName:
                !Join
                    - ''
                    - - !Ref CADS3BucketForWebSite
                      - .s3.amazonaws.com
              Id: !Ref CADS3BucketForWebSite
              OriginPath: '/contactflowsite'
              S3OriginConfig:
                OriginAccessIdentity:
                    !Join
                        - ''
                        - - 'origin-access-identity/cloudfront/'
                          - !Ref CADCloudFrontDistributionAccessIdentity
            Enabled: 'true'
            Logging:
                Bucket: !GetAtt createWebSiteS3Bucket.DomainName
                Prefix: 'logs/'
                IncludeCookies: 'true'
            Comment: CloudFront for contact flow apis
            DefaultRootObject: connectflows.html
            DefaultCacheBehavior:
                AllowedMethods:
                    - DELETE
                    - GET
                    - HEAD
                    - OPTIONS
                    - PATCH
                    - POST
                    - PUT
                TargetOriginId: !Ref CADS3BucketForWebSite
                ForwardedValues:
                    QueryString: true
                    Cookies:
                        Forward: all
                ViewerProtocolPolicy: redirect-to-https
            Restrictions:
                GeoRestriction:
                    RestrictionType: whitelist
                    Locations:
                        - US

    CADWebsiteCreatorRole:
        Type: "AWS::IAM::Role"
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - "lambda.amazonaws.com"
                Action:
                  - "sts:AssumeRole"
          Path: "/"
          Policies:
            -
              PolicyName: !Sub ${AWS::StackName}-contact-flow-creator-policy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - 'logs:CreateLogGroup'
                      - 'logs:CreateLogStream'
                      - 'logs:PutLogEvents'
                    Resource:
                      - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:PutObject"
                      - "s3:GetObject"
                      - "s3:PutObjectAcl"
                    Resource:
                      -  !Join
                          - ''
                          - - 'arn:'
                            - !Ref 'AWS::Partition'
                            - ':s3:::'
                            - !Ref CADS3BucketForWebSite
                            - '/*'
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:PutBucketPublicAccessBlock"
                    Resource:
                      -  !Join
                          - ''
                          - - 'arn:'
                            - !Ref 'AWS::Partition'
                            - ':s3:::'
                            - !Ref CADS3BucketForWebSite
                  -
                    Effect: "Allow"
                    Action:
                      - "s3:GetObject"
                    Resource:
                      -  !Join
                          - ''
                          - - 'arn:'
                            - !Ref 'AWS::Partition'
                            - ':s3:::'
                            - 'amazon-connect-blogs2'
                            - '/*'

    webSiteCreator:
      Type: "AWS::Lambda::Function"
      Properties:
        Description:  >
            AWS Lambda Function that will create the website and upload it to the S3 bucket
        Handler: "index.handler"
        Role: !GetAtt CADWebsiteCreatorRole.Arn
        Runtime: "nodejs12.x"
        MemorySize: 256
        Timeout: 120
        Code: ./website-creator/
        
    invokeWebSiteCreator:
        Type: Custom::CreateWebSite
        DependsOn: createWebSiteS3Bucket
        Properties:  
            ServiceToken:  !GetAtt webSiteCreator.Arn
            customAction: configureWebsite
            Region: !Ref AWS::Region
            sourceS3Bucket: "amazon-connect-blogs2"
            sourceS3key: "2020/contactflows"
            destS3Bucket: !Ref CADS3BucketForWebSite
            destS3KeyPrefix: contactflowsite
            manifestLocation: "2020/contactflows/web-site-manifest.json"